version: "3.8"

services:
  db:
    image: mysql:8.0
    ports:
      - 3307:3306
    env_file:
      - .env.test 
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: testdb
    volumes:
      - mysql_test_data:/var/lib/mysql

volumes:
  mysql_test_data: