version: "3.2"

services:
  suapc-admin-service-front:
    image: suapc-admin-service-front
    container_name: suapc-admin-service-front
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
